apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    email: no-reply@cluster.dev # TODO: Change email to customers one
    privateKeySecretRef:
      name: letsencrypt-dns
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - selector:
        dnsZones:
          - "${dns_zones}"
      dns01:
        route53:
          region: ${aws_region}
          #hostedZoneID: DIKER8JEXAMPLE # optional, see policy above
          #role: arn:aws:iam::XXXXXXXXXXXX:role/dns-manager
