---
apiVersion: v1
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  url: https://argocd.olm-voatsap.shalb.org
  oidc.config: |
    name: keycloak
    issuer: https://keycloak.olm-voatsap.shalb.org/auth/realms/kubernetes
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    g, ArgoCDAdmins, role:admin
