on:
  push:
    paths:
      - 'entrypoint.sh'
      - 'bin/**'
      - 'terraform/**'
      - 'kubernetes/apps/**'
      - 'Dockerfile'
      - '.github/workflows/**'
      - '.cluster.dev/**'
      - 'action.yaml'
    branches:
      - master
jobs:
  deploy_cluster_job:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
      CLUSTER_CONFIG_PATH: "./.cluster.dev/"
      VERBOSE_LVL: DEBUG
    runs-on: ubuntu-latest
    name: Cluster.dev
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Reconcile Clusters
      id: reconcile
      uses: shalb/cluster.dev@master
    - name: Get the Cluster Credentials
      run: echo -e "\n\033[1;32m${{ steps.reconcile.outputs.ssh }}\n\033[1;32m${{ steps.reconcile.outputs.kubeconfig }}\n\033[1;32m${{ steps.reconcile.outputs.argocd }}"
