on:
  push:
    paths:
      - './.cluster.dev/digitalocean-k8s.yaml'
    branches:
      - master
jobs:
  deploy_cluster_job:
    runs-on: ubuntu-latest
    name: Deploy and Update K8s Clusters
    steps:
    # To use this repository's private action, you must check out the repository
    - name: Checkout Repo
      uses: actions/checkout@v2
    # - uses: ./ # Uses an action in the root directory
    - name: Reconcile Clusters
      id: reconcile
      uses: shalb/cluster.dev@master
      with:
        cluster-config: './.cluster.dev/digitalocean-k8s.yaml'
    # For user and password please use your token name and token hash
    # https://www.digitalocean.com/docs/apis-clis/api/create-personal-access-token/
        cloud-user: ${{ secrets.DO_TOKEN_NAME }}
        cloud-pass: ${{ secrets.DIGITALOCEAN_TOKEN }}
    # Use the output from the `reconcile` step
    - name: Get the Cluster Credentials
      run: echo -e "\n\033[1;32m${{ steps.reconcile.outputs.ssh }}\n\033[1;32m${{ steps.reconcile.outputs.kubeconfig }}\n\033[1;32m${{ steps.reconcile.outputs.argocd }}"
