on: [push]

jobs:
  deploy_cluster_job:
    runs-on: ubuntu-latest
    name: A job to read cluster yaml definition
    steps:
    # To use this repository's private action, you must check out the repository
    - name: Checkout
      uses: actions/checkout@v1
    - uses: ./ # Uses an action in the root directory
    - name: Valiadte Target
      id: validate
      uses: shalb/cluster.dev@master
      with:
        cluster-config: './.cluster.dev/minikube-one.yaml'
        cloud-user: 'someuser'
        cloud-pass: 'somepass'
    # Use the output from the `hello` step
    - name: Get the execution status
      run: echo "The status ${{ steps.validate.outputs.status }}"