
on:
  push:
    branches-ignore:
    - master
jobs:
  deploy_cluster_job:
    runs-on: ubuntu-latest
    name: Deploy and Update K8s Clusters
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }} # BRANCH_NAME
    - name: Reconcile Clusters
      id: reconcile
      uses: shalb/cluster.dev@${{ github.ref }} # BRANCH_NAME
      with:
        cluster-config: ./.cluster.dev/${{ github.ref }}.yaml # CLUSTER_CONFIG_PATH
        cloud-user: ${{ secrets.aws_access_key_id }}
        cloud-pass: ${{ secrets.aws_secret_access_key }}
      if: test -f "./.cluster.dev/${{ github.ref }}.yaml" # CLUSTER_CONFIG_PATH
    - name: Get the execution status
      run: echo "The status ${{ steps.reconcile.outputs.status }}"

# TODO: Auto-cleanup after branch deletion
# See: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onevent_nametypes
# See: https://help.github.com/en/actions/reference/events-that-trigger-workflows#delete-event-delete
# Can be triggered as PR closing - https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
# Or every evening: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
